# site_name: ${{values.component_id}}
# site_description: ${{values.description}}
site_name: kftc-website
site_description: KFTC's main homepage
repo_url: https://github.com/ecosoonil/kftc-website
edit_uri: edit/main/docs

plugins:
  - techdocs-core

nav:
  - Overview: overview.md
